name: Bootcamp 15 Demo
run-name: Testing Github Actions
on: [push]
jobs:
  Test-GithubActions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Automatically triggered test event"
      - run: echo "CICD Class Bootcamp 15"
      - name: Checkout code from repo
        uses: actions/checkout@v4
      - run: echo "The repository has been cloned"
      - run: "Testing the runner or VM"
      - name: List files in the repository
        run: |
          ls ${{github.workspace}}
